export let PlacesData =[{
    place:"bus stand",
    address:"kapoori market Raja park",
    isClean:true,
    beforeImage:"",
    afterImage:"",
    ward:20,
    inCharge:"Sukh dev",
    cleanTime:"",
    cleanDate:"",
    placeId:"800561PLC001"
},{
    place:"railway station",
    address:" Raja park",
    isClean:true,
    beforeImage:"",
    afterImage:"",
    ward:17,
    inCharge:"Sukh dev",
    cleanTime:"",
    cleanDate:"",
    placeId:"800561PLC002"
},{
    place:"circle",
    address:"kapoori market Raja park",
    isClean:false,
    beforeImage:"",
    afterImage:"",
    ward:20,
    inCharge:"Sukh dev",
    cleanTime:"",
    cleanDate:"",
    placeId:"800561PLC003"
},{
    place:"highway",
    address:"kapoori market Raja park",
    isClean:false,
    beforeImage:"",
    afterImage:"",
    ward:20,
    inCharge:"Sukh dev",
    cleanTime:"",
    cleanDate:"",
    placeId:"800561PLC004"
},{
    place:"market",
    otherDetails:"",
    address:"Bada bazar SNG Road",
    isClean:false,
    beforeImage:"",
    afterImage:"",
    ward:1,
    inCharge:"Sukh dev",
    cleanTime:"",
    cleanDate:"",
    placeId:"800561PLC005"
},{
    place:"market",
    otherDetails:"",
    address:"Bada bazar SNG Road",
    isClean:true,
    beforeImage:"",
    afterImage:"",
    ward:1,
    inCharge:"Sukh dev",
    cleanTime:"",
    cleanDate:"",
    placeId:"800561PLC0016"
},{
    place:"others",
    otherDetails:"",
    address:"Bada bazar SNG Road",
    isClean:true,
    beforeImage:"",
    afterImage:"",
    ward:1,
    inCharge:"Sukh dev",
    cleanTime:"",
    cleanDate:"",
    placeId:"800561PLC006"
},{
    place:"others",
    otherDetails:"",
    address:"Bada bazar SNG Road",
    isClean:false,
    beforeImage:"",
    afterImage:"",
    ward:1,
    inCharge:"Sukh dev",
    cleanTime:"",
    cleanDate:"",
    placeId:"800561PLC007"
},{
    place:"circle",
    otherDetails:"",
    address:"Bada bazar SNG Road",
    isClean:true,
    beforeImage:"",
    afterImage:"",
    ward:1,
    inCharge:"Sukh dev",
    cleanTime:"",
    cleanDate:"",
    placeId:"800561PLC009"
},{
    place:"market",
    otherDetails:"",
    address:"Bada bazar SNG Road",
    isClean:true,
    beforeImage:"",
    afterImage:"",
    ward:1,
    inCharge:"Sukh dev",
    cleanTime:"",
    cleanDate:"",
    placeId:"800561PLC010"
},{
    place:"highway",
    otherDetails:"",
    address:"Bada bazar SNG Road",
    isClean:false,
    beforeImage:"",
    afterImage:"",
    ward:1,
    inCharge:"Sukh dev",
    cleanTime:"",
    cleanDate:"",
    placeId:"800561PLC011"
},{
    place:"others",
    otherDetails:"",
    address:"Bada bazar SNG Road",
    isClean:true,
    beforeImage:"",
    afterImage:"",
    ward:1,
    inCharge:"Sukh dev",
    cleanTime:"",
    cleanDate:"",
    placeId:"800561PLC012"
},{
    place:"railway station",
    otherDetails:"",
    address:"Bada bazar SNG Road",
    isClean:false,
    beforeImage:"",
    afterImage:"",
    ward:1,
    inCharge:"Sukh dev",
    cleanTime:"",
    cleanDate:"",
    placeId:"800561PLC013"
},{
    place:"bus stand",
    otherDetails:"",
    address:"Bada bazar SNG Road",
    isClean:true,
    beforeImage:"",
    afterImage:"",
    ward:1,
    inCharge:"Sukh dev",
    cleanTime:"",
    cleanDate:"",
    placeId:"800561PLC0014"
},{
    place:"highway",
    otherDetails:"",
    address:"Hawa mahel",
    isClean:true,
    beforeImage:"",
    afterImage:"",
    ward:10,
    inCharge:"Sukh dev",
    cleanTime:"",
    cleanDate:"",
    placeId:"800561PLC0015"
}
]